#!/bin/sh

SRC_DIR="$HOME/git/xmonad-exe"
export STACK_YAML="$SRC_DIR/stack.yaml"

if [ "$#" -ne 1 ]; then
	echo "Invalid usage."
	exit 1
fi

TMP="$(mktemp -p "$HOME"/.cache)"

stack build &&
rm -f "$1" &&
cp "$SRC_DIR/$(stack path --dist-dir)/build/xmonad-exe/xmonad-exe" "$1"
