#!/bin/sh

SRC_DIR="$HOME/git/xmonad-exe"

if [ "$#" -ne 1 ]; then
	echo "Invalid usage."
	exit 1
fi

(cd "$SRC_DIR" && cabal new-build) &&
rm -f "$1" &&
find "$SRC_DIR/dist-newstyle" -type f -executable -name xmonad-exe -exec cp '{}' "$1" ';'
